# Generated by Django 2.1 on 2018-08-26 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('family', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentLecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ServerRestAPI.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('family', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherLecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LectureID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ServerRestAPI.Lecture')),
                ('TeacherID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ServerRestAPI.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='studentlecture',
            name='TeacherLectureID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ServerRestAPI.TeacherLecture'),
        ),
    ]
